"""
attendance/infrastructure/models.py
─────────────────────────────────────
SQLAlchemy ORM models for the attendance module.
ONLY this layer touches the database. Domain entities are pure Python.
"""
import uuid
from datetime import datetime, time
from decimal import Decimal

from app.core.database import Base, TimestampMixin
from app.shared.enums.attendance import (AttendanceSource, AttendanceStatus,
                                         CheckType)
from sqlalchemy import (Boolean, Date, DateTime, Enum, Float, ForeignKey,
                        Index, Integer, Numeric, String, Time,
                        UniqueConstraint, func)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship


class AttendancePolicyModel(Base, TimestampMixin):
    """Company-level attendance configuration. One row per company."""
    __tablename__ = "attendance_policies"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    company_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("companies.id"), unique=True, nullable=False)

    late_tolerance_minutes: Mapped[int] = mapped_column(Integer, default=15)
    early_leave_tolerance_minutes: Mapped[int] = mapped_column(Integer, default=15)
    overtime_threshold_minutes: Mapped[int] = mapped_column(Integer, default=30)
    max_work_minutes_per_day: Mapped[int] = mapped_column(Integer, default=600)
    checkin_window_before_minutes: Mapped[int] = mapped_column(Integer, default=60)
    require_selfie: Mapped[bool] = mapped_column(Boolean, default=True)
    require_gps: Mapped[bool] = mapped_column(Boolean, default=True)
    allow_wfh: Mapped[bool] = mapped_column(Boolean, default=False)


class OvertimePolicyModel(Base, TimestampMixin):
    """Company overtime multipliers. One row per company."""
    __tablename__ = "overtime_policies"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    company_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("companies.id"), unique=True, nullable=False)

    multiplier_weekday: Mapped[Decimal] = mapped_column(Numeric(3, 1), default=Decimal("1.5"))
    multiplier_weekend: Mapped[Decimal] = mapped_column(Numeric(3, 1), default=Decimal("2.0"))
    multiplier_holiday: Mapped[Decimal] = mapped_column(Numeric(3, 1), default=Decimal("3.0"))
    max_overtime_per_day: Mapped[int] = mapped_column(Integer, default=180)  # minutes
    requires_approval: Mapped[bool] = mapped_column(Boolean, default=True)


class ShiftModel(Base, TimestampMixin):
    """Shift pattern template."""
    __tablename__ = "shifts"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    company_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("companies.id"), nullable=False)
    name: Mapped[str] = mapped_column(String(100), nullable=False)
    start_time: Mapped[time] = mapped_column(Time, nullable=False)
    end_time: Mapped[time] = mapped_column(Time, nullable=False)
    break_minutes: Mapped[int] = mapped_column(Integer, default=60)
    is_overnight: Mapped[bool] = mapped_column(Boolean, default=False)
    work_days: Mapped[str] = mapped_column(String(7), default="1111100")  # Mon-Sun bitmask


class ShiftAssignmentModel(Base, TimestampMixin):
    """Links employee to a shift for a date range."""
    __tablename__ = "shift_assignments"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    employee_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("employees.id"), nullable=False)
    shift_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("shifts.id"), nullable=False)
    start_date: Mapped[datetime] = mapped_column(Date, nullable=False)
    end_date: Mapped[datetime | None] = mapped_column(Date, nullable=True)  # None = current


class WorkCalendarModel(Base):
    """
    Pre-generated grid: one row per employee per working day.
    Generated by Celery task at start of each month.
    Drives rekap queries — never calculate on the fly.
    """
    __tablename__ = "work_calendars"
    __table_args__ = (
        UniqueConstraint("company_id", "employee_id", "date"),
        Index("idx_wc_emp_date", "employee_id", "date"),
        Index("idx_wc_company_date", "company_id", "date"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    company_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("companies.id"), nullable=False)
    employee_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("employees.id"), nullable=False)
    date: Mapped[datetime] = mapped_column(Date, nullable=False)
    shift_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey("shifts.id"), nullable=True)
    is_workday: Mapped[bool] = mapped_column(Boolean, default=True)
    is_holiday: Mapped[bool] = mapped_column(Boolean, default=False)
    holiday_name: Mapped[str | None] = mapped_column(String(200), nullable=True)


class AttendanceLogModel(Base):
    """
    APPEND-ONLY raw event log. Never update a row here.
    One row per check-in or check-out action.
    """
    __tablename__ = "attendance_logs"
    __table_args__ = (
        Index("idx_att_log_emp_ts", "employee_id", "timestamp_utc"),
        Index("idx_att_log_company_date", "company_id", "timestamp_utc"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    employee_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("employees.id"), nullable=False)
    company_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("companies.id"), nullable=False)
    timestamp_utc: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    type: Mapped[str] = mapped_column(String(20), nullable=False)  # stored as 'check_in'/'check_out'
    latitude: Mapped[float | None] = mapped_column(Float, nullable=True)
    longitude: Mapped[float | None] = mapped_column(Float, nullable=True)
    accuracy_meters: Mapped[float | None] = mapped_column(Float, nullable=True)
    photo_url: Mapped[str | None] = mapped_column(String, nullable=True)
    device_id: Mapped[str | None] = mapped_column(String(200), nullable=True)
    source: Mapped[str] = mapped_column(String(20), default='mobile')  # stored as 'mobile'/'web'/'admin_override'
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class AttendanceSummaryModel(Base, TimestampMixin):
    """
    Computed daily attendance result per employee.
    Recalculable from raw logs. One row per employee per date.
    """
    __tablename__ = "attendance_summaries"
    __table_args__ = (
        UniqueConstraint("employee_id", "date"),
        Index("idx_att_sum_emp_date", "employee_id", "date"),
        Index("idx_att_sum_company_date", "company_id", "date"),
        Index("idx_att_sum_status", "company_id", "status", "date"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    employee_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("employees.id"), nullable=False)
    company_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("companies.id"), nullable=False)
    date: Mapped[datetime] = mapped_column(Date, nullable=False)
    shift_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey("shifts.id"), nullable=True)

    check_in_time: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    check_out_time: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    work_minutes: Mapped[int] = mapped_column(Integer, default=0)
    late_minutes: Mapped[int] = mapped_column(Integer, default=0)
    early_leave_minutes: Mapped[int] = mapped_column(Integer, default=0)
    overtime_minutes: Mapped[int] = mapped_column(Integer, default=0)

    is_late: Mapped[bool] = mapped_column(Boolean, default=False)
    is_early_leave: Mapped[bool] = mapped_column(Boolean, default=False)
    is_alpha: Mapped[bool] = mapped_column(Boolean, default=False)
    is_leave: Mapped[bool] = mapped_column(Boolean, default=False)

    status: Mapped[str] = mapped_column(
        String(20), default='incomplete', index=True  # stored as 'present'/'late'/'alpha' etc
    )
    processed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


class OvertimeRequestModel(Base, TimestampMixin):
    """Employee overtime request, linked to generic approvals table."""
    __tablename__ = "overtime_requests"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    employee_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("employees.id"), nullable=False)
    company_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("companies.id"), nullable=False)
    date: Mapped[datetime] = mapped_column(Date, nullable=False)
    start_time: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    end_time: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    overtime_minutes: Mapped[int] = mapped_column(Integer, nullable=False)
    reason: Mapped[str] = mapped_column(String(500), nullable=False)
    status: Mapped[str] = mapped_column(String(20), default="pending")
    approved_by: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    approved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
